version: "2"
services:
  app:
    container_name: hospitality-node
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend



networks:
  backend:

volumes:
  db-data:

